# Generated by Django 4.2.30 on 2026-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='0', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
